version: "3.9"             # Compose sürümü

services:                  # Servisleri tanımlar
  app:                     # Bu bizim Django uygulamamız Django’da “app” = projedeki belli bir işlevi yapan küçük modül.
    build:                 # Dockerfile nerede?
      context: .           # Bu dizinde
      args:
        - DEV=true
    ports:                 # Host:Container port eşleşmesi
      - "8000:8000"
    volumes:               # Kodları container içine bağla (hot reload)
      - ./app:/app
      - dev-static-data:/vol/web
    command: >             # Konteyner çalışınca şu komutu çalıştır
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db


  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data:
  dev-static-data:
