version: "3.9"

services:
  app:
    build:
      context: .
    environment:
      - DB_NAME=dbname
      - DB_USER=rootuser
      - DB_PASS=changeme
      - DJANGO_SECRET_KEY=changeme
      - DJANGO_ALLOWED_HOSTS=ec2-18-156-171-169.eu-central-1.compute.amazonaws.com,18.156.171.169,localhost,127.0.0.1
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 8000:8000
    volumes:
      - static-data:/vol/static


volumes:
  postgres-data:
  static-data:
